memberaudit/urls.py
from django.urls import path

from . import views

app_name = "memberaudit"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path("add_character", views.add_character, name="add_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "share_character/<int:character_pk>/",
        views.share_character,
        name="share_character",
    ),
    path(
        "unshare_character/<int:character_pk>/",
        views.unshare_character,
        name="unshare_character",
    ),
    path(
        "character_assets_data/<int:character_pk>/",
        views.character_assets_data,
        name="character_assets_data",
    ),
    path(
        "character_asset_container/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container,
        name="character_asset_container",
    ),
    path(
        "character_asset_container_data/<int:character_pk>/<int:parent_asset_pk>/",
        views.character_asset_container_data,
        name="character_asset_container_data",
    ),
    path(
        "character_contacts_data/<int:character_pk>/",
        views.character_contacts_data,
        name="character_contacts_data",
    ),
    path(
        "character_contracts_data/<int:character_pk>/",
        views.character_contracts_data,
        name="character_contracts_data",
    ),
    path(
        "character_contract_details/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_details,
        name="character_contract_details",
    ),
    path(
        "character_contract_items_included_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_included_data,
        name="character_contract_items_included_data",
    ),
    path(
        "character_contract_items_requested_data/<int:character_pk>/<int:contract_pk>/",
        views.character_contract_items_requested_data,
        name="character_contract_items_requested_data",
    ),
    path(
        "character_corporation_history/<int:character_pk>/",
        views.character_corporation_history,
        name="character_corporation_history",
    ),
    path(
        "character_implants_data/<int:character_pk>/",
        views.character_implants_data,
        name="character_implants_data",
    ),
    path(
        "character_loyalty_data/<int:character_pk>/",
        views.character_loyalty_data,
        name="character_loyalty_data",
    ),
    path(
        "character_jump_clones_data/<int:character_pk>/",
        views.character_jump_clones_data,
        name="character_jump_clones_data",
    ),
    path(
        "character_mail_headers_by_label_data/<int:character_pk>/<int:label_id>/",
        views.character_mail_headers_by_label_data,
        name="character_mail_headers_by_label_data",
    ),
    path(
        "character_mail_headers_by_list_data/<int:character_pk>/<int:list_id>/",
        views.character_mail_headers_by_list_data,
        name="character_mail_headers_by_list_data",
    ),
    path(
        "character_mail/<int:character_pk>/<int:mail_pk>/",
        views.character_mail,
        name="character_mail",
    ),
    path(
        "character_skillqueue_data/<int:character_pk>/",
        views.character_skillqueue_data,
        name="character_skillqueue_data",
    ),
    path(
        "character_skills_data/<int:character_pk>/",
        views.character_skills_data,
        name="character_skills_data",
    ),
    path(
        "character_skill_sets_data/<int:character_pk>/",
        views.character_skill_sets_data,
        name="character_skill_sets_data",
    ),
    path(
        "character_wallet_journal_data/<int:character_pk>/",
        views.character_wallet_journal_data,
        name="character_wallet_journal_data",
    ),
    path(
        "character_wallet_transactions_data/<int:character_pk>/",
        views.character_wallet_transactions_data,
        name="character_wallet_transactions_data",
    ),
    path("character_finder", views.character_finder, name="character_finder"),
    path(
        "character_finder_data",
        views.character_finder_data,
        name="character_finder_data",
    ),
    path("reports", views.reports, name="reports"),
    path(
        "user_compliance_report_data",
        views.user_compliance_report_data,
        name="user_compliance_report_data",
    ),
    path(
        "corporation_compliance_report_data",
        views.corporation_compliance_report_data,
        name="corporation_compliance_report_data",
    ),
    path(
        "skill_sets_report_data",
        views.skill_sets_report_data,
        name="skill_sets_report_data",
    ),
    path(
        "character_skill_set_details/<int:character_pk>/<int:skill_set_pk>",
        views.character_skill_set_details,
        name="character_skill_set_details",
    ),
    path(
        "character_attributes_data/<int:character_pk>",
        views.character_attribute_data,
        name="character_attribute_data",
    ),
    path("data-export/", views.data_export, name="data_export"),
    path(
        "data-export/run-update/<str:topic>",
        views.data_export_run_update,
        name="data_export_run_update",
    ),
    path(
        "data-export/download/<str:topic>",
        views.download_export_file,
        name="download_export_file",
    ),
]

memberaudit/templates/memberaudit/base.html
{% extends 'allianceauth/base.html' %}

{% block page_title %}
    {{ page_title|striptags }} - {{ app_title }}
{% endblock %}

{% block content %}
    <br />
    <div class="aa-memberaudit">
        {% include 'memberaudit/partials/menu.html' %}
        <h2 class="text-left">{{ page_title }}</h2>
        {% block details %}{% endblock %}
    </div>
{% endblock %}

memberaudit/templates/memberaudit/character_finder.html
{% extends 'memberaudit/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}


{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate 'Characters' %}</h3>
        </div>

        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-width-fix" id="tab_characters">
                    <thead>
                        <tr>
                            <th>{% translate 'Character<br>Name' %}</th>
                            <th>{% translate 'Character<br>Organization' %}</th>
                            <th>{% translate 'Character<br>Location' %}</th>
                            <th>{% translate 'Main<br>Name' %}</th>
                            <th>{% translate 'Main<br>Organization' %}</th>
                            <th>{% translate 'Main<br>State' %}</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody></tbody>
                </table>
            </div>
            <p class="text-muted">
                <i class="fas fa-crown"></i> Main character&nbsp;•&nbsp;
                <i class="far fa-eye"></i> Currently shared with recruiters
            </p>
        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

    <!--load JS for filterDropDown plugin -->
    <script type="text/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}">
    </script>

    <script>
        $(document).ready(function() {
            $('#tab_characters').DataTable({
                ajax: {
                    url: '{% url 'memberaudit:character_finder_data' %}',
                    dataSrc: '',
                    cache: false
                },

                columns: [
                    {
                        data: 'character',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'character_organization' },
                    { data: 'location' },
                    { data: 'main_character' },
                    { data: 'main_organization' },
                    { data: 'state_name' },
                    { data: 'actions' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                    { data: 'region_name' },
                    { data: 'solar_system_name' },
                    { data: 'main_alliance_name' },
                    { data: 'main_corporation_name' },
                    { data: 'main_str' },
                ],

                columnDefs: [
                    { "orderable": false, "targets": [ 6 ] },
                    { "visible": false, "targets": [ 7, 8, 9, 10, 11, 12, 13 ] },
                ],

                order: [ [ 0, "asc" ] ],

                filterDropDown: {
                    columns: [
                        {
                            idx: 7,
                            title: "{% translate 'Char Alliance' %}"
                        },
                        {
                            idx: 8,
                            title: "{% translate 'Char Corporation' %}"
                        },
                        {
                            idx: 9,
                            title: "{% translate 'Char Region' %}"
                        },
                        {
                            idx: 10,
                            title: "{% translate 'Char Solar System' %}"
                        },
                        {
                            idx: 11,
                            title: "{% translate 'Main Alliance' %}"
                        },
                        {
                            idx: 12,
                            title: "{% translate 'Main Corporation' %}"
                        },
                        {
                            idx: 13,
                            title: "{% translate 'Is Main?' %}"
                        },
                        {
                            idx: 5,
                            title: "{% translate 'Main State' %}"
                        }

                    ],
                    bootstrap: true
                }
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/character_finder.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}

{% endblock %}

memberaudit/templates/memberaudit/data_export.html
{% extends 'memberaudit/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Topics' %}</h3>
        </div>
        <div class="panel-body">
            <table id="tbl_data_exports" class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Rows</th>
                    <th>Export file age</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for topic in topics %}
                        <tr>
                            <td>{{ topic.title }}</td>
                            <td>{{ topic.description }}</td>
                            <td>{{ topic.rows|intcomma }}</td>
                            <td>{{ topic.last_updated_at|timesince|default:"no file" }}</td>
                            <td>
                                {% if topic.has_file %}
                                    <a class="btn btn-primary" href="{% url 'memberaudit:download_export_file' topic.value %}">Download</a>
                                {% else %}
                                    <a class="btn btn-primary" href="#" disabled>Download</a>
                                {% endif %}
                                {% if topic.update_allowed %}
                                    <a class="btn btn-default" href="{% url 'memberaudit:data_export_run_update' topic.value %}">Update now</a>
                                {% else %}
                                    <a class="btn btn-default" href="#" disabled>Update now</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class="text-muted">
                Export files contain the complete data of all <strong>{{ character_count|intcomma }}</strong> characters known to Member Audit. They are in CSV format and zipped. Existing export files can updated after {{ minutes_until_next_update }} minutes.
            </p>
        </div>
    </div>
{% endblock details %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/data_export.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

memberaudit/templates/memberaudit/launcher.html
{% extends 'memberaudit/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Characters' %}</h3>
        </div>
        <div class="panel-body">
            <!-- Characters -->
            <div class="character-cards">
                <ul class="cards_container">
                    <!-- Add New Character -->
                    <li class="cards_item">
                        <div class="card">
                            <div class="card-header">{% translate 'Register Character' %}</div>

                            <div class="card-body card__content">
                                <a href="{% url 'memberaudit:add_character' %}">
                                    <img src="{{ 1|character_portrait_url:256 }}" alt="Add character">
                                </a>
                            </div>

                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:add_character' %}">{% translate 'Register' %}</a>
                            </div>
                        </div>
                    </li>

                    {% if has_registered_characters %}
                        <!-- Registered Characters -->
                        {% for auth_character in auth_characters|dictsort:"character_name" %}
                            <li class="cards_item">
                                <div class="card">
                                    <div class="card-header">
                                        {{ auth_character.character_name }}
                                        {% if auth_character.character_id == main_character_id %}
                                            &nbsp;<i class="fas fa-crown" title="Main character"></i>
                                        {% endif %}
                                        {% if auth_character.character.is_shared %}
                                            &nbsp;<i class="far fa-eye" title="Currently shared with recruiters"></i>
                                        {% endif %}
                                    </div>

                                    <div class="card-body card__content">
                                        <p>
                                            <a href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}">
                                                <span class="aa-memberaudit-launcher-character-image">
                                                    <img src="{{ auth_character.character_id|character_portrait_url:256 }}" alt="{{ auth_character.character_name }}">

                                                    {% if auth_character.alliance_id %}
                                                        <span class="aa-memberaudit-alliance-logo">
                                                            <img class="" src="{{ auth_character.alliance_id|alliance_logo_url:64 }}" title="{{ auth_character.alliance_name }}">
                                                        </span>
                                                    {% endif %}

                                                    <span class="aa-memberaudit-corporation-logo">
                                                        <img class="" src="{{ auth_character.corporation_id|corporation_logo_url:64 }}" title="{{ auth_character.corporation_name }}">
                                                    </span>
                                                </span>
                                            </a>
                                        </p>

                                        <div class="text-center">
                                            {% include 'memberaudit/partials/solar_system.html' with character=auth_character.character only %}<br>
                                            {% if auth_character.character.wallet_balance %}
                                                {{ auth_character.character.wallet_balance.total|intword|default_if_none:"-" }} ISK<br>
                                            {% else %}
                                                <span class="text-muted">{% translate "(no data yet)" %}</span>
                                            {% endif %}

                                        </div>
                                    </div>

                                    <div class="card-footer">
                                        <a class="btn btn-success btn-sm" href="{% url 'memberaudit:character_viewer' auth_character.character.pk %}"
                                            role="button" title="{% translate 'View this character.' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                        </a>

                                        {% if perms.memberaudit.share_characters %}
                                            {% if auth_character.character.is_shared %}
                                                <a class="btn btn-primary btn-sm" href="{% url 'memberaudit:unshare_character' auth_character.character.pk %}"
                                                    role="button" title="{% translate 'Disable access to this character for recruiters.' %}">
                                                    <i class="far fa-eye-slash"></i>
                                                </a>
                                            {% else %}
                                                <a class="btn btn-warning btn-sm" href="{% url 'memberaudit:share_character' auth_character.character.pk %}"
                                                    role="button"
                                                    onclick="return confirm('Are you sure you want to SHARE this character?')"
                                                    title="{% translate 'Enable access to this character for recruiters.' %}">
                                                    <i class="far fa-eye"></i>
                                                </a>
                                            {% endif %}
                                        {% endif %}

                                        <a class="btn btn-danger btn-sm" href="{% url 'memberaudit:remove_character' auth_character.character.pk %}"
                                            role="button" title="{% translate 'Remove this character.' %}"
                                            onclick="return confirm('Are you sure you want to REMOVE this character?')">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            {% if unregistered_chars|length > 0 %}
                <p class="text-info">
                    <strong>{% translate 'Unregistered character(s):' %}&nbsp;&nbsp;</strong>
                    {{ unregistered_chars|join:", " }}
                </p>
            {% endif %}

            <p class="text-muted">
                <i class="fas fa-crown"></i> Main character&nbsp;•&nbsp;
                <i class="far fa-eye"></i> Currently shared with recruiters
            </p>
        </div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

memberaudit/templates/memberaudit/reports.html
{% extends 'memberaudit/base.html' %}

{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}
    <div>
        {% include 'memberaudit/partials/reports/tabs_navigation.html' %}

        <div class="panel panel-default panel-tabs">
            <div class="panel-body">
                <!-- Tab panes -->
                <div class="tab-content">
                    {% include 'memberaudit/partials/reports/tabs/user_compliance.html' %}
                    {% include 'memberaudit/partials/reports/tabs/corporation_compliance.html' %}
                    {% include 'memberaudit/partials/reports/tabs/skill_sets.html' %}
                </div>
            </div>

        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/dataTables.rowGroup.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#tab_user_compliance').DataTable({
                ajax: {
                    url: '{% url 'memberaudit:user_compliance_report_data' %}',
                    dataSrc: '',
                    cache: false
                },
                columns: [
                    {
                        data: 'main',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'state' },
                    {
                        data: 'organization',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'registered_str' },
                    { data: 'compliance_str' },
                    { data: 'total_chars' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                ],
                columnDefs: [
                    { "visible": false, "targets": [ 6, 7 ] },
                ],
                order: [ [ 0, "asc" ] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 1,
                            title: "{% translate 'State' %}"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Alliance' %}"
                        },
                        {
                            idx: 7,
                            title: "{% translate 'Corporation' %}"
                        },
                        {
                            idx: 3,
                            title: "{% translate 'Registered?' %}"
                        },
                        {
                            idx: 4,
                            title: "{% translate 'Compliant?' %}"
                        }
                    ],
                    bootstrap: true
                },
                createdRow: function( row, data, dataIndex )
                {
                    if (data['is_compliant']){
                        $(row).addClass('success');
                    }
                    else if (data['is_registered']){
                        $(row).addClass('warning');
                    }
                    else {
                        $(row).addClass('danger');
                    }
                }
            });

            $('#tab_corporation_compliance').DataTable({
                ajax: {
                    url: '{% url 'memberaudit:corporation_compliance_report_data' %}',
                    dataSrc: '',
                    cache: false
                },
                columns: [
                    {
                        data: 'organization_html',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: 'mains_count' },
                    { data: 'characters_count' },
                    { data: 'compliance_percent' },
                    /* hidden columns */
                    { data: 'alliance_name' },
                    { data: 'corporation_name' },
                    { data: 'is_compliant_str' },
                ],
                columnDefs: [
                    { "visible": false, "targets": [ 4, 5, 6 ] },
                ],
                order: [ [ 0, "asc" ] ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 4,
                            title: "{% translate 'Alliance' %}"
                        },
                        {
                            idx: 5,
                            title: "{% translate 'Corporation' %}"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Compliant?' %}"
                        },
                    ],
                    autoSize: false,
                    bootstrap: true
                },
                createdRow: function( row, data, dataIndex )
                {
                    if (data['is_compliant']){
                        $(row).addClass('success');
                    }
                    else if (data['is_partly_compliant']){
                        $(row).addClass('warning');
                    }
                    else {
                        $(row).addClass('danger');
                    }
                }
            });

            $('#tab_skill_sets').DataTable({
                ajax: {
                    url: "{% url 'memberaudit:skill_sets_report_data' %}",
                    dataSrc: '',
                    cache: false
                },
                columns: [
                    { data: 'group' },
                    { data: 'main_html' },
                    { data: 'state' },
                    { data: 'organization_html' },
                    { data: 'character_html' },
                    { data: 'has_required' },

                    /* hidden columns */
                    { data: 'alliance' },
                    { data: 'corporation' },
                    { data: 'has_required_str' },
                    { data: 'is_doctrine_str' },
                    { data: 'is_main_str' },
                ],
                order: [[0, "asc"], [1, "asc"], [4, "asc"]],
                rowGroup: {
                    dataSrc: 'group',
                    className: 'table-group'
                },
                columnDefs: [
                    { "visible": false, "targets": [0, 6, 7, 8, 9] }
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 0,
                            title: "{% translate 'Groups' %}"
                        },
                        {
                            idx: 2,
                            title: "{% translate 'State' %}"
                        },
                        {
                            idx: 6,
                            title: "{% translate 'Alliance' %}"
                        },
                        {
                            idx: 7,
                            title: "{% translate 'Corporation' %}"
                        },
                        {
                            idx: 8,
                            title: "{% translate 'Required Skills?' %}"
                        },
                        {
                            idx: 9,
                            title: "{% translate 'Doctrine?' %}"
                        },
                        {
                            idx: 10,
                            title: "{% translate 'Is Main?' %}"
                        }
                    ],
                    autoSize: false,
                    bootstrap: true
                }
            });

        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'memberaudit/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/memberaudit.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'memberaudit/css/reports.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}

{% endblock %}